orders/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

orders/order_func/urls.py
from django.urls import path

from . import views

app_name = "order_func"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

orders/orders/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # HTML route
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("order_func.urls", namespace="order_func")),
    path("", include("orders_app.urls", namespace="orders_app")),
    path("account/", include("account.urls")),
    # REST API route
    path("api/orders_app/", include("orders_app.urls_api")),
    path("api/cart/", include("cart.urls_api")),
    path("api/order_func/", include("order_func.urls_api")),
    path("api/account/", include("account.urls_api")),
]

orders/orders_app/urls.py
from django.urls import path

from . import views

app_name = "orders_app"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

orders/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

orders/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from orders_app.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    Представление для добавления товара в корзину.

    Получает объект продукта по его ID, валидирует форму CartAddProductForm
    и добавляет товар в корзину (с указанным количеством и параметром
    перезаписи количества).

    Args:
        request (HttpRequest): Объект запроса (должен содержать POST-данные).
        product_id (int): ID продукта, который нужно добавить.

    Returns:
        HttpResponseRedirect: перенаправление на страницу корзины
        ("cart:cart_detail").
    """

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    """
    Представление для удаления товара из корзины.

    Получает объект продукта по его ID и удаляет его из корзины.

    Args:
        request (HttpRequest): Объект запроса.
        product_id (int): ID продукта, который нужно удалить.

    Returns:
        HttpResponseRedirect: перенаправление на страницу корзины
        ("cart:cart_detail").
    """

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    """
    Представление для отображения содержимого корзины.

    Для каждого товара в корзине добавляется форма обновления количества.
    Возвращает страницу с деталями корзины.

    Args:
        request (HttpRequest): Объект запроса.

    Returns:
        HttpResponse: шаблон "cart/detail.html" с данными корзины.
    """

    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

orders/cart/templates/cart/detail.html
{% extends "orders_app/base.html" %}
{% load static %}

{% block title %}
  Корзина
{% endblock %}

{% block content %}
  <h1>Ваша корзина</h1>
  <table class="cart">
    <thead>
      <tr>
<!--        <th>Image</th>-->
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за шт</th>
        <th>Всего</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
<!--            <td>-->
<!--              <a href="{{ product.get_absolute_url }}">-->
<!--                <img src="{% if product.image %}{{ product.image.url }}-->
<!--                {% else %}{% static "img/no_image.png" %}{% endif %}">-->
<!--              </a>-->
<!--            </td>-->
<!--            <td>{{ product.name }}</td>-->
            <td>
              <a href="{{ product.get_absolute_url }}">
                {{ product.name }}
              </a>
            </td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Изменить">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="Удалить">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">₽{{ item.price }}</td>
            <td class="num">₽{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Итого</td>
        <td colspan="3"></td>
        <td class="num">₽{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "orders_app:product_list" %}" class="button
    light">Продолжить покупки</a>
    <a href="{% url "order_func:order_create" %}" class="button">Завершить</a>
  </p>
{% endblock %}